server:
  port: 8080
  fe_url: http://localhost:3000

postgres:
  host: host
  port: 5432
  user: user
  password: password
  db_name: dbname
  ssl_mode: disable

jwt:
  secret: secret

google_oauth:
  redirect_url: http://localhost:8080/auth/signin/google/callback
  client_id: client_id
  client_secret: client_secret
  state: state
