// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/ryanadiputraa/unclatter/app/auth"

	mock "github.com/stretchr/testify/mock"
)

// AuthProviderRepository is an autogenerated mock type for the AuthProviderRepository type
type AuthProviderRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, authProvider
func (_m *AuthProviderRepository) Save(ctx context.Context, authProvider auth.AuthProvider) error {
	ret := _m.Called(ctx, authProvider)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.AuthProvider) error); ok {
		r0 = rf(ctx, authProvider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthProviderRepository creates a new instance of AuthProviderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthProviderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthProviderRepository {
	mock := &AuthProviderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
