name: Build and Deploy to Railway App

on:
  push:
    branches: [deploy/railway]

jobs:
  build-and-push:
    name: Build and deploy to Railway app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and tag image
        env:
          PORT: :80
          FE_URL: https://unclatter.devzy.my.id
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: 5432
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: unclatter
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_REDIRECT_URL: https://api-unclatter.devzy.my.id/auth/signin/google/callback
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_STATE: ${{ secrets.GOOGLE_STATE }}

        run: |
          docker build \
            --build-arg PORT=$PORT \
            --build-arg FE_URL=$FE_URL \
            --build-arg POSTGRES_HOST=$POSTGRES_HOST \
            --build-arg POSTGRES_PORT=$POSTGRES_PORT \
            --build-arg POSTGRES_USER=$POSTGRES_USER \
            --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            --build-arg POSTGRES_DB=$POSTGRES_DB \
            --build-arg JWT_SECRET=$JWT_SECRET \
            --build-arg GOOGLE_REDIRECT_URL=$GOOGLE_REDIRECT_URL \
            --build-arg GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
            --build-arg GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
            --build-arg GOOGLE_STATE=$GOOGLE_STATE \
            -t ryanadiputra/unclatter:latest .

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service unclatter
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
