name: Run unit test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
        id: go

      - name: Check out code into the Go module repository
        uses: actions/checkout@v4

      - name: Run test cases
        run: |
          go test ./... -v -cover
